name: aco_plus
description: A new Flutter project.

publish_to: "none"

version: 0.0.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #FIREBASE
  firebase_core: ^2.15.0
  firebase_analytics: ^10.4.5
  firebase_crashlytics: ^3.0.15

  #UI
  overlay_support: ^2.0.1
  material_symbols_icons: ^4.2661.1

  #OUTROS
  intl: ^0.18.0
  rxdart: ^0.27.4
  shared_preferences: ^2.2.2
  flutter_native_splash: ^2.2.0+1
  validators: ^3.0.0
  image_picker: ^1.0.5
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  in_app_review: ^2.0.8
  share_plus: ^7.2.2
  flutter_keyboard_visibility: ^6.0.0
  permission_handler: ^11.1.0
  path_provider: ^2.1.2
  dio: ^5.4.0
  flutter_masked_text2: ^0.9.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  url_launcher: ^6.2.4
  location: ^5.0.3
  cpf_cnpj_validator: ^2.0.0
  qr_flutter: ^4.1.0
  pdf: ^3.10.7
  cloud_firestore: ^4.15.5
  firebase_storage: ^11.6.6
  pdfx: ^2.6.0
  syncfusion_flutter_charts: ^24.2.7+1
  syncfusion_flutter_datagrid_export: ^24.2.7
  syncfusion_flutter_xlsio: ^24.2.7
  string_validator: ^1.0.2
  camera: ^0.10.5+9
  fluttertoast: ^8.2.4
  pdfrx: ^0.4.54

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/launcher/launcher.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"

flutter_native_splash:
  android: true
  ios: true
  color: "#FFFFFF"
  image: assets/launcher/splash.png
  android_12:
    image: assets/launcher/splash.png
    icon_background_color: "#FFFFFF"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/launcher/

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/work_sans/WorkSans-Black.ttf
          weight: 900

        - asset: assets/fonts/work_sans/WorkSans-BlackItalic.ttf
          weight: 900
          style: italic

        - asset: assets/fonts/work_sans/WorkSans-ExtraBold.ttf
          weight: 800

        - asset: assets/fonts/work_sans/WorkSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        - asset: assets/fonts/work_sans/WorkSans-Bold.ttf
          weight: 700

        - asset: assets/fonts/work_sans/WorkSans-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/work_sans/WorkSans-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/work_sans/WorkSans-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: assets/fonts/work_sans/WorkSans-Medium.ttf
          weight: 500

        - asset: assets/fonts/work_sans/WorkSans-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/work_sans/WorkSans-Regular.ttf
          weight: 400

        - asset: assets/fonts/work_sans/WorkSans-Light.ttf
          weight: 300

        - asset: assets/fonts/work_sans/WorkSans-LightItalic.ttf
          weight: 300
          style: italic

        - asset: assets/fonts/work_sans/WorkSans-ExtraLight.ttf
          weight: 200

        - asset: assets/fonts/work_sans/WorkSans-ExtraLightItalic.ttf 
          weight: 200
          style: italic

        - asset: assets/fonts/work_sans/WorkSans-Thin.ttf
          weight: 100

        - asset: assets/fonts/work_sans/WorkSans-ThinItalic.ttf
          weight: 100
          style: italic
